title: <p align="center"> Jerin Varghese </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jerinvarghese/">LinkedIn</a> |
  <a href="https://github.com/jerinv">GitHub</a>
  </p>
  
  <p align="justify">
  I am currently a Data Scientist for the Division of Industry Productivity Studies at the U.S. Bureau of Labor Statistics.
  <br><br>
  I graduated from Johns Hopkins University with a M.S. in Applied Economics, and graduated from the University of Maryland
  with a B.A. in Economics and Mathematics.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-VQDLRS3LMG # Google Analytics tracking ID
